#!/data/data/com.termux/files/usr/bin/bash
# on_server — step 2: enable daemons, deploy nginx config, generate the
# control-api auth token, and bring up pm2 (control-api + telegram-bot).
#
# Run after install.sh:
#   bash server/scripts/setup-services.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVER_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONTROL_API_DIR="$SERVER_DIR/control-api"
NGINX_DEMO_DIR="$SERVER_DIR/services/nginx/demo"
NGINX_TEMPLATE="$SERVER_DIR/services/nginx/nginx.conf.template"

: "${PREFIX:?PREFIX is not set — this script must be run inside Termux}"

echo "==> on_server setup-services.sh starting"

echo "==> Enabling termux-services daemons (nginx, redis, postgresql, sshd)"
for svc in nginx redis postgresql sshd; do
  sv-enable "$svc" || echo "    (sv-enable $svc failed or already enabled, continuing)"
done

echo "==> Initializing postgresql data directory (first run only)"
if [ ! -d "$PREFIX/var/lib/postgresql/base" ]; then
  initdb "$PREFIX/var/lib/postgresql" || echo "    initdb failed or already initialized, continuing"
fi

echo "==> Deploying nginx config from template"
CONTROL_API_PORT="8420"
if [ -f "$PREFIX/etc/nginx/nginx.conf" ] && [ ! -f "$PREFIX/etc/nginx/nginx.conf.orig" ]; then
  cp "$PREFIX/etc/nginx/nginx.conf" "$PREFIX/etc/nginx/nginx.conf.orig"
  echo "    backed up original config to nginx.conf.orig"
fi
sed \
  -e "s#__NGINX_DEMO_ROOT__#$NGINX_DEMO_DIR#g" \
  -e "s#__NGINX_PREFIX__#$PREFIX#g" \
  -e "s#__CONTROL_API_PORT__#$CONTROL_API_PORT#g" \
  -e "s#__PHP_FPM_SOCK__#127.0.0.1:9000#g" \
  "$NGINX_TEMPLATE" > "$PREFIX/etc/nginx/nginx.conf"
echo "    nginx.conf written (demo root: $NGINX_DEMO_DIR, control-api port: $CONTROL_API_PORT)"

echo "==> Starting php-fpm (not termux-services managed, started directly)"
php-fpm -D 2>/dev/null || echo "    php-fpm may already be running, continuing"

echo "==> Generating control-api auth token"
TOKEN="$(openssl rand -hex 32)"
ON_SERVER_TOKEN="$TOKEN" node -e "
const { loadConfig, saveConfig, CONFIG_PATH } = require('$CONTROL_API_DIR/src/config.js');
const cfg = loadConfig();
cfg.token = process.env.ON_SERVER_TOKEN;
saveConfig(cfg);
console.log('    token written to ' + CONFIG_PATH);
"

echo "==> Starting nginx/redis/postgresql/sshd"
for svc in nginx redis postgresql sshd; do
  sv up "$svc" || echo "    (sv up $svc failed, check 'sv status $svc' manually)"
done

echo "==> Starting control-api + telegram-bot under pm2"
(cd "$CONTROL_API_DIR" && pm2 start ecosystem.config.js)
pm2 save

echo "==> Writing Termux:Boot start script (~/.termux/boot/start-on-server.sh)"
mkdir -p "$HOME/.termux/boot"
BOOT_SCRIPT="$HOME/.termux/boot/start-on-server.sh"
cat > "$BOOT_SCRIPT" <<EOF
#!$PREFIX/bin/bash
# Auto-generated by setup-services.sh — runs on boot via Termux:Boot
# (requires the separate "Termux:Boot" app to be installed from
# F-Droid/Play and opened once so Android allows it to run at startup).
termux-wake-lock

for svc in nginx redis postgresql sshd; do
  sv up "\$svc" 2>/dev/null || true
done

php-fpm -D 2>/dev/null || true

pm2 resurrect
EOF
chmod +x "$BOOT_SCRIPT"
echo "    wrote $BOOT_SCRIPT"

# Best-effort IP discovery so the user has something to paste into the
# Flutter app's Settings screen immediately (LAN IP — the tailnet IP comes
# from setup-tailscale.sh, run next).
IP_ADDR="unknown (check manually with 'ip addr' or your Android WiFi settings)"
if command -v ip >/dev/null 2>&1; then
  CANDIDATE="$(ip -4 addr show wlan0 2>/dev/null | awk '/inet /{print $2}' | cut -d/ -f1)"
  [ -n "$CANDIDATE" ] && IP_ADDR="$CANDIDATE"
elif command -v ifconfig >/dev/null 2>&1; then
  CANDIDATE="$(ifconfig wlan0 2>/dev/null | awk '/inet /{print $2}' | sed 's/addr://')"
  [ -n "$CANDIDATE" ] && IP_ADDR="$CANDIDATE"
fi
if [ "$IP_ADDR" = "unknown (check manually with 'ip addr' or your Android WiFi settings)" ] && command -v termux-wifi-connectioninfo >/dev/null 2>&1; then
  CANDIDATE="$(termux-wifi-connectioninfo 2>/dev/null | node -e "let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>{try{console.log(JSON.parse(d).ip||'')}catch(e){}})")"
  [ -n "$CANDIDATE" ] && IP_ADDR="$CANDIDATE"
fi

echo ""
echo "================================================================"
echo " on_server setup-services.sh complete"
echo "================================================================"
echo " Your control-api token:  $TOKEN"
echo " -> paste this into the Flutter app's Settings screen"
echo ""
echo " Phone LAN IP (best guess): $IP_ADDR"
echo " control-api:  http://$IP_ADDR:8420"
echo " nginx demo:   http://$IP_ADDR:8080"
echo ""
echo " Next: bash server/scripts/setup-tailscale.sh (for remote access"
echo " beyond your local WiFi)."
echo "================================================================"
